### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by Umity** [MetalPetal/HighlightShadow#1]
How can we install this? Can you please set up as swift package?

**Comment by YuAo** [comment]
We do not currently have a SwiftPM setup for this repo. However you can just drag the source files to your project to use them. 

You may want to change `@"shadowHighlightAdjust"` in https://github.com/MetalPetal/HighlightShadow/blob/59a8a99a4aa438ac733e749f732de5da22be8e88/Sources/MTIHighlightShadowFilter.m#L22
to `@"metalpetalshadowhighlight::shadowHighlightAdjust"` if your deployment target >= iOS 13. 

See: https://github.com/MetalPetal/MetalPetal/issues/206

**Comment by Umity** [comment]
if i drag them then #import getting error
<MetalPetal/MetalPetal.h> 'MetalPetal/MetalPetal.h' file not found in MTIHighlightShadowFilter.h file

**Comment by Umity** [comment]
i changed to #import <MetalPetal.h> and problem resolved but now i cant get the filter
 let shadowhighFilter = MTIHighlightShadowFilter()
returning error, Cannot find 'MTIHighlightShadowFilter' in scope

**Comment by Umity** [comment]
OK, i thought xcode auto adding line 
#import "MTIHighlightShadowFilter.h"
to my bridging header but i manually added instead and that seem sorted the problem.

**Comment by YuAo** [comment]
Also, I think it's quite easy to rewrite this filter in Swift. There are only ~40 lines of objective-c code.

**Comment by Umity** [comment]
`Also, I think it's quite easy to rewrite this filter in Swift. There are only ~40 lines of objective-c code.`

It could be great if you can.. I loved this filter, and it is much better approach then my highlights/shadows adjustments on rgbcurvetool.
